apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: Deploying a sample nextjs application.
  annotations:
    github.com/project-slug: backstage/demo
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: production
  consumesApis:
    - demo-graphql
