

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: This is a nxstjs website for farmshop
  tags:
    - nodejs
    - backend
spec:
  type: website
  lifecycle: production
  owner: dev


