# Component definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: A Next.js application
  annotations:
    github.com/project-slug: Realsammy/FarmShop
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: website
  owner: infrastructure-team
  lifecycle: production
  system: fullstack-system
  consumesApis:
    - nextjs-api

---

# API definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nextjs-api
  description: API exposed by the Next.js application
spec:
  type: openapi
  lifecycle: production
  owner: infrastructure-team
  definition:
    #$text: https://your-docs-url/openapi.json
  apiConsumedBy:
    - nextjs-app

---

# Location definition for the GitHub repository
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: nextjs-repo
spec:
  type: url
  target: https://github.com/Realsammy/FarmShop/blob/master/catalog-info.yaml
