

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontstore
  description: This is a nxstjs website for farmshop
  tags:
    - nodejs
    - backend
spec:
  type: service
  lifecycle: production
  owner: dev


