# Component definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: Deploying a sample nextjs application.
  annotations:
    github.com/project-slug: backstage/demo
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: production
  consumesApis:
    - demo-graphql

---
# API definition for demo-graphql
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-graphql
  description: A sample GraphQL API used by the Next.js application
spec:
  type: graphql
  lifecycle: production
  owner: backstage/maintainers
  definition:
    $text: |
      type Query {
        hello: String
      }

---
# Group definition for backstage maintainers
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: maintainers
  description: The Backstage maintainers team
spec:
  type: team
  profile:
    displayName: Backstage Maintainers
  parent: backstage

---
# Group definition for backstage
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The Backstage organization
spec:
  type: organization
  profile:
    displayName: Backstage
