# Component definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: Deploying a sample Next.js application.
  annotations:
    github.com/project-slug: backstage/demo
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: website
  owner: backstage/maintainers
  lifecycle: production
  consumesApis:
    - demo-graphql

---
# API definition for demo-graphql
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-graphql
  description: A sample GraphQL API used by the Next.js application
spec:
  type: graphql
  lifecycle: production
  owner: backstage/maintainers
  definition:
    $text: |
      type Query {
        hello: String
      }

---
# Group definition for backstage/maintainers (corrected)
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage/maintainers
  description: The Backstage maintainers team
spec:
  type: group  # Correct type for group definition
  profile:
    displayName: Backstage Maintainers
  parent: backstage  # Ensure the parent group exists

---
# Group definition for backstage (if it doesn't exist)
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The Backstage organization
spec:
  type: organization  # Type for an organization
  profile:
    displayName: Backstage
