apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nestjs-webshop
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: realsammy86
  system: websopping
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - artist-api
