# Component definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app-unique
  description: A Next.js application
  annotations:
    github.com/project-slug: Realsammy/FarmShop
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: website
  owner: infrastructure-team
  lifecycle: production
  system: fullstack-system
  consumesApis:
    - nextjs-api
---

# Location definition for the GitHub repository
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: nextjs-repo-unique
spec:
  type: url
  target: https://github.com/Realsammy/FarmShop/blob/master/catalog-info.yaml
