apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: infrastructure-team
  system: shopping
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - artist-api
