# Component definition for the Next.js application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextjs-app
  description: A Next.js application
  tags:
    - nextjs
    - frontend
    - react
  annotations:
    backstage.io/techdocs-ref: url:https://your-docs-url
spec:
  type: website
  lifecycle: production
  owner: infrastructure-team
  system: fullstack-system
  providesApis:
    - your-nextjs-api

#---

# Location definition for the GitHub repository
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: nextjs-repo
spec:
  type: url
  target: https://github.com/Realsammy/FarmShop
